### ISSUE TITLE
login trouble

### ISSUE THREAD

**Issue by obeyler** [frodenas/harbor-boshrelease#2]
After deploy a file tmp/deployments-vars.yml is created 
It contains value used during deployments such as
harbor_initial_admin_password: 0mv8hgua0202dyw3kxxx

but when I try to connect on ui by using admin/0mv8hgua0202dyw3kxxx
The login page always said that the password is invalid.

**Comment by frodenas** [comment]
This repo was a personal experiment that is no longer maintained. Please consider forking it.
